### PR TITLE
Upgrade flv.js

### PR DESCRIPTION
**Pull request by kevin940726**
Related to https://github.com/17media/17live/issues/1068.

This PR just merge master from origin. Hopefully fix the issue.

### CODE REVIEW

**Comment by arthur17media** [comment]
I sync this branch with the latest of `Bilibili:accurate-sample-duration` and we should rebase the [build commit](https://github.com/17media/flv.js/commit/088b3d3e3eb7f5aa31535d945cc8b27e77abfb13) after merging.

**Comment by kevin940726** [comment]
@arthur17media Yep just that I'm not sure that the latest of that branch fix the issue or not. We can test both ways though.

Oops I missed that build commit. Maybe we can just publish it to npm to avoid the hassle?

**Comment by arthur17media** [comment]
@kevin940726 If publish the private repo is easy, then we can do it

**Comment by kevin940726** [comment]
@arthur17media I don't think we have to make this private? Is there any concern about this?

**Comment by arthur17media** [comment]
@kevin940726 
If we need to implement 17Q, I think we need to keep it private right ?
But after we publish it, any one install our library also have the ability to get the SEI data 😂

**Comment by kevin940726** [comment]
Not necessary IMO, frontend code is always public anyways.

**Pull request closed without merging**
